default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: alpha
  password:


development:
  <<: *default
  database: remote_development
test:
  <<: *default
  database: remote_test
production:
  <<: *default
  database: remote_production
